namespace Claude.AgentSdk.Metrics;

/// <summary>
///     Metrics event fired when token usage or cost changes occur.
/// </summary>
public sealed record MetricsEvent
{
    /// <summary>
    ///     The session ID this event belongs to.
    /// </summary>
    public required string SessionId { get; init; }

    /// <summary>
    ///     Input tokens sent to the API.
    /// </summary>
    public int InputTokens { get; init; }

    /// <summary>
    ///     Output tokens generated by Claude.
    /// </summary>
    public int OutputTokens { get; init; }

    /// <summary>
    ///     Input tokens served from prompt cache.
    /// </summary>
    public int? CacheReadInputTokens { get; init; }

    /// <summary>
    ///     Input tokens written to prompt cache.
    /// </summary>
    public int? CacheCreationInputTokens { get; init; }

    /// <summary>
    ///     Cost in USD for this turn.
    /// </summary>
    public double? CostUsd { get; init; }

    /// <summary>
    ///     Total duration in milliseconds.
    /// </summary>
    public int DurationMs { get; init; }

    /// <summary>
    ///     API-specific duration in milliseconds.
    /// </summary>
    public int ApiDurationMs { get; init; }

    /// <summary>
    ///     Whether this result was an error.
    /// </summary>
    public bool IsError { get; init; }

    /// <summary>
    ///     Number of turns in the conversation so far.
    /// </summary>
    public int NumTurns { get; init; }

    /// <summary>
    ///     When this event occurred.
    /// </summary>
    public DateTimeOffset Timestamp { get; init; } = DateTimeOffset.UtcNow;

    /// <summary>
    ///     Display name for this session (user-defined).
    /// </summary>
    public string? DisplayName { get; init; }

    /// <summary>
    ///     The model used for this turn (e.g., "claude-sonnet-4-20250514").
    /// </summary>
    public string? Model { get; init; }
}
